### Delivery Delay Prediction

In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [27]:
df = pd.read_csv("C:\\Users\\ABHISHEK\\Desktop\\Data Co Supply chaine model\\supply_chain_cleaned_dataset.csv")

In [28]:
df.info

<bound method DataFrame.info of             Type  Days for shipping (real)  Days for shipment (scheduled)  \
0          DEBIT                         3                              4
1       TRANSFER                         5                              4
2           CASH                         4                              4
3          DEBIT                         3                              4
4        PAYMENT                         2                              4
...          ...                       ...                            ...
180514      CASH                         4                              4
180515     DEBIT                         3                              2
180516  TRANSFER                         5                              4
180517   PAYMENT                         3                              4
180518   PAYMENT                         4                              4

        Benefit per order  Sales per customer   Delivery Status  \
0               91.250000          314.640015  Advance shipping
1             -249.089996          311.359985     Late delivery
2             -247.779999          309.720001  Shipping on time
3               22.860001          304.809998  Advance shipping
4              134.210007          298.250000  Advance shipping
...                   ...                 ...               ...
180514          40.000000          399.980011  Shipping on time
180515        -613.770019          395.980011     Late delivery
180516         141.110001          391.980011     Late delivery
180517         186.229996          387.980011  Advance shipping
180518         168.949997          383.980011  Shipping on time

        Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                        0           73  Sporting Goods        Caguas  ...
1                        1           73  Sporting Goods        Caguas  ...
2                        0           73  Sporting Goods      San Jose  ...
3                        0           73  Sporting Goods   Los Angeles  ...
4                        0           73  Sporting Goods        Caguas  ...
...                    ...          ...             ...           ...  ...
180514                   0           45         Fishing      Brooklyn  ...
180515                   1           45         Fishing   Bakersfield  ...
180516                   1           45         Fishing       Bristol  ...
180517                   0           45         Fishing        Caguas  ...
180518                   0           45         Fishing        Caguas  ...

       Order_year  Order_month Order_day delay_days  delivery_time  \
0            2018            1        31          0              3
1            2018            1        13          0              5
2            2018            1        13          0              4
3            2018            1        13          0              3
4            2018            1        13          0              2
...           ...          ...       ...        ...            ...
180514       2016            1        16          0              4
180515       2016            1        16          0              3
180516       2016            1        15          0              5
180517       2016            1        15          0              3
180518       2016            1        15          0              4

       profit_margin  order_value_category  order_month order_weekday  \
0           0.278413                  High            1             2
1          -0.760000                  High            1             5
2          -0.756003                  High            1             5
3           0.069748                  High            1             5
4           0.409489                  High            1             5
...              ...                   ...          ...           ...
180514      0.100005                  High            1             5
180515     -1.534502                  High            1             5
180516      0.352793                  High            1             4
180517      0.465598                  High            1             4
180518      0.422396                  High            1             4

       order_value
0       327.750000
1       327.750000
2       327.750000
3       327.750000
4       327.750000
...            ...
180514  399.980011
180515  399.980011
180516  399.980011
180517  399.980011
180518  399.980011

[180519 rows x 54 columns]>

In [29]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order_year,Order_month,Order_day,delay_days,delivery_time,profit_margin,order_value_category,order_month,order_weekday,order_value
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,2018,1,31,0,3,0.278413,High,1,2,327.75
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,2018,1,13,0,5,-0.760000,High,1,5,327.75
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,2018,1,13,0,4,-0.756003,High,1,5,327.75
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,2018,1,13,0,3,0.069748,High,1,5,327.75
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,2018,1,13,0,2,0.409489,High,1,5,327.75

In [30]:
drop_cols = [
    "Order Id",
    "Order Item Id",
    "Customer Id",
    "Customer Email",
    "Customer Password",
    "Product Name"
]
df = df.drop(drop_cols, axis=1, errors="ignore")

In [31]:
le = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col].astype(str))

In [32]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order_year,Order_month,Order_day,delay_days,delivery_time,profit_margin,order_value_category,order_month,order_weekday,order_value
0,1,3,4,91.250000,314.640015,0,0,73,40,66,...,2018,1,31,0,3,0.278413,0,1,2,327.75
1,3,5,4,-249.089996,311.359985,1,1,73,40,66,...,2018,1,13,0,5,-0.760000,0,1,5,327.75
2,0,4,4,-247.779999,309.720001,3,0,73,40,452,...,2018,1,13,0,4,-0.756003,0,1,5,327.75
3,1,3,4,22.860001,304.809998,0,0,73,40,285,...,2018,1,13,0,3,0.069748,0,1,5,327.75
4,2,2,4,134.210007,298.250000,0,0,73,40,66,...,2018,1,13,0,2,0.409489,0,1,5,327.75

In [33]:
drop_cols = [
    "Delivery Status",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "delivery_time"
]

df = df.drop(drop_cols, axis=1, errors="ignore")

In [34]:
X = df.drop("Late_delivery_risk", axis=1)

In [35]:
X

,Type,Benefit per order,Sales per customer,Category Id,Category Name,Customer City,Customer Country,Customer Segment,Customer State,Department Id,...,Shipping Mode,Order_year,Order_month,Order_day,delay_days,profit_margin,order_value_category,order_month,order_weekday,order_value
0,1,91.250000,314.640015,73,40,66,1,0,36,2,...,3,2018,1,31,0,0.278413,0,1,2,327.750000
1,3,-249.089996,311.359985,73,40,66,1,0,36,2,...,3,2018,1,13,0,-0.760000,0,1,5,327.750000
2,0,-247.779999,309.720001,73,40,452,0,0,5,2,...,3,2018,1,13,0,-0.756003,0,1,5,327.750000
3,1,22.860001,304.809998,73,40,285,0,2,5,2,...,3,2018,1,13,0,0.069748,0,1,5,327.750000
4,2,134.210007,298.250000,73,40,66,1,1,36,2,...,3,2018,1,13,0,0.409489,0,1,5,327.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,0,40.000000,399.980011,45,18,59,0,2,31,7,...,3,2016,1,16,0,0.100005,0,1,5,399.980011
180515,1,-613.770019,395.980011,45,18,26,0,1,5,7,...,2,2016,1,16,0,-1.534502,0,1,5,399.980011
180516,3,141.110001,391.980011,45,18,55,0,1,7,7,...,3,2016,1,15,0,0.352793,0,1,4,399.980011
180517,2,186.229996,387.980011,45,18,66,1,0,36,7,...,3,2016,1,15,0,0.465598,0,1,4,399.980011
180518,2,168.949997,383.980011,45,18,66,1,0,36,7,...,3,2016,1,15,0,0.422396,0,1,4,399.980011

In [36]:
y = df["Late_delivery_risk"]

In [37]:
y

0         0
1         1
2         0
3         0
4         0
         ..
180514    0
180515    1
180516    1
180517    0
180518    0
Name: Late_delivery_risk, Length: 180519, dtype: int64

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [39]:
model = LogisticRegression(max_iter=1000)

In [40]:
model.fit(X_train, y_train)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [41]:
print(model.score(X_test, y_test))

0.7867456976142995

In [42]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,confusion_matrix

In [43]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("confusion_matrix", confusion_matrix(y_test, y_pred))
print("precision_score", precision_score(y_test, y_pred))
print("f1_score", f1_score(y_test, y_pred))

Accuracy: 0.7867456976142995
confusion_matrix [[18224  6187]
 [ 5362 24383]]
precision_score 0.7976120379456983
f1_score 0.8085219265522673

In [44]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.75      0.76     24411
           1       0.80      0.82      0.81     29745

    accuracy                           0.79     54156
   macro avg       0.79      0.78      0.78     54156
weighted avg       0.79      0.79      0.79     54156

In [45]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (126363, 45)
X_test shape: (54156, 45)

### Random Forest Model

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [48]:
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=6
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=6)

In [49]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7016581726863136

In [50]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.63      0.84      0.72     24411
           1       0.82      0.58      0.68     29745

    accuracy                           0.70     54156
   macro avg       0.72      0.71      0.70     54156
weighted avg       0.73      0.70      0.70     54156

In [51]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (126363, 45)
X_test shape: (54156, 45)